# Generated by Django 3.0.7 on 2020-06-27 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200627_2145'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Offer',
            new_name='Offers',
        ),
        migrations.RenameModel(
            old_name='Product',
            new_name='Products',
        ),
    ]
